#! /usr/bin/env bash

set -eu -o pipefail

VERSION="go1.17"

GOLANG_VERSION=$(go version)
if [[ $GOLANG_VERSION = *$VERSION* ]]; then
  echo "Golang $GOLANG_VERSION installed"
else
  echo "Golang $VERSION is required to run this project! Found $GOLANG_VERSION"
  echo "Install go with 'brew install go'"
  echo "or if that version is ahead of ${GOLANG_VERSION} then run:"
  echo "Run 'brew install ${GOLANG_VERSION} && brew link --force ${GOLANG_VERSION}' to install"
  exit 1
fi
